title: "Ahmad Shahzad | AI Engineer & Automation Architect"
description: "Portfolio showcasing AI, Automation, and Edge-AI projects"
theme: jekyll-theme-minimal
show_downloads: false
google_analytics: 
